<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZSIfxPy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZSIfxPy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZSIfxPy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZSIfxPy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZSIfxPy\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZSIfxPy',
    'container.build_id' => '4d99c60f',
    'container.build_time' => 1588625397,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZSIfxPy');
