<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBqWYS5d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBqWYS5d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBqWYS5d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBqWYS5d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBqWYS5d\App_KernelDevDebugContainer([
    'container.build_hash' => 'BqWYS5d',
    'container.build_id' => 'b71912af',
    'container.build_time' => 1588876061,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBqWYS5d');
