<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'app_lucky_number' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/lucky/number']], [], []],
    'app_lucky_print_number' => [['number'], ['_controller' => 'App\\Controller\\LuckyController::print_number'], [], [['variable', '/', '[^/]++', 'number', true], ['text', '/lucky/number']], [], []],
    'productscategories_search' => [[], ['_controller' => 'App\\Controller\\ProductCategoryController::showProductsCategories'], [], [['text', '/productscategories']], [], []],
    'productcategory_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductCategoryController::edit'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/productcategory/edit']], [], []],
    'productcategory_create' => [[], ['_controller' => 'App\\Controller\\ProductCategoryController::new'], [], [['text', '/productcategory/new']], [], []],
    'product_show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], []],
    'products_show' => [[], ['_controller' => 'App\\Controller\\ProductController::showProducts'], [], [['text', '/products']], [], []],
    'product_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductController::edit'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/product/edit']], [], []],
    'product_save' => [[], ['_controller' => 'App\\Controller\\ProductController::save'], [], [['text', '/product/save']], [], []],
    'save_product_default' => [[], ['_controller' => 'App\\Controller\\ProductController::save_product_default'], [], [['text', '/product/save_product_default']], [], []],
    'save_product_ajax' => [[], ['_controller' => 'App\\Controller\\ProductController::save_product_ajax'], [], [['text', '/product/save_product_ajax}']], [], []],
    'product_create' => [[], ['_controller' => 'App\\Controller\\ProductController::new'], [], [['text', '/product']], [], []],
    'save_product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::SaveProduct'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/product/save']], [], []],
    'store' => [[], ['_controller' => 'App\\Controller\\StoreController::startpage'], [], [['text', '/store']], [], []],
];
